server:
  port: 8080
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
       - id: search-service
        uri: lb://search-service
        predicates:
        - Path=/search/v1/**
      - id: restaurant-service
        uri: lb://restaurant-service
        predicates:
        - Path=/restaurants/v1/**
      - id: order-service
        uri: lb://order-service
        predicates:
        - Path=/orders/v1/**
      - id: driver-service
        uri: lb://driver-service
        predicates:
        - Path=/drivers/v1/**
      - id: invoice-service
        uri: lb://invoice-service
        predicates:
        - Path=/invoices/v1/**
      - id: customer-service
        uri: lb://customer-service
        predicates:
        - Path=/customers/v1/**
        
        