server:
  port: 8080
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
      - id: restaurant-service
        uri: http://localhost:8082/
        predicates:
        - Path=/restaurants/v1/**
      - id: order-service
        uri: http://localhost:8085/
        predicates:
        - Path=/orders/v1/**
      - id: driver-service
        uri: http://localhost:9095/
        predicates:
        - Path=/drivers/v1/**
      - id: invoice-service
        uri: http://localhost:8086/
        predicates:
        - Path=/invoices/v1/**