server:
  port: 8081
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
      - id: customerService
        uri: http://localhost:8081/
        predicates:
        - Path=/customers/v1/**
      - id: driverService
        uri: http://localhost:8082/
        predicates:
        - Path=/drivers/v1/**
      - id: restaurantService
        uri: http://localhost:8082/
        predicates:
        - Path=/restaurants/v1/**
      - id: restaurantService
        uri: http://localhost:8082/
        predicates:
        - Path=/orders/v1/**