server:
  port: 8081
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
      - id: orderService
        uri: http://localhost:8085/
        predicates:
        - Path=/orders/v1/**
      - id: restaurantService
        uri: http://localhost:8082/
        predicates:
        - Path=/restaurants/v1/**