server:
  port: 8086

spring:
  application:
    name: security-service
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/food_order
    username: root
    password: root
