server:
  port: 9095

spring:
  application:
    name: driver-service
  data:
    mongodb:
      #uri: mongodb://localhost:27017/food_order
      uri: mongodb+srv://fosuser:fospassword@fos-cluster-0.ycnnt.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
freedriver:
  distance: 5      